name: FAST-VQA-with-Conv-Backbone-Resize-MultiLevel

num_epochs: 60
l_num_epochs: 10
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 16
num_workers: 6

need_upsampled: false
need_feat: false
need_fused: false

wandb:
    project_name: VQA_Experiments_2022

model:
    type: DiViDeAddEvaluator
    args:
        backbone_size: conv_tiny
        backbone_preserve_keys: fragments
        divide_head: true # if true, different branches will not share head
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
 

    
        
